-- models/gold/fact_listings_metrics.sql
{{ config(materialized='table') }}

SELECT
  "HOST_ID",
  "SCRAPED_DATE",  
  "LISTING_ID",
  "HAS_AVAILABILITY",
  "HOST_IS_SUPERHOST",
  "LISTING_NEIGHBOURHOOD",
  SUM("PRICE") AS "PRICE",
  COUNT(*) AS "TOTAL_STAYS",
  SUM(30 - "AVAILABILITY_30") AS "NUMBER_OF_STAYS",
  SUM("PRICE" * (30 - "AVAILABILITY_30")) AS "ESTIMATED_REVENUE",
  AVG("REVIEW_SCORES_RATING") AS "AVERAGE_RATING"
FROM {{ ref('silver_airbnb_listings') }}
WHERE "HAS_AVAILABILITY" = 't'
GROUP BY "LISTING_ID",
"SCRAPED_DATE",  
  "HOST_ID","HAS_AVAILABILITY","HOST_IS_SUPERHOST","LISTING_NEIGHBOURHOOD"
